// <auto-generated />
using ChangeLens.Infrastructure.LocalState.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChangeLens.Infrastructure.LocalState.Persistence.Migrations
{
    [DbContext(typeof(ChangeLensLocalStateDbContext))]
    [Migration("20260726150843_InitialLocalState")]
    partial class InitialLocalState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ChangeLens.Infrastructure.LocalState.Persistence.Entities.ApplicationLocalState", b =>
                {
                    b.Property<int>("SingletonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("singleton_id");

                    b.Property<string>("ColorTheme")
                        .HasColumnType("TEXT")
                        .HasColumnName("color_theme");

                    b.Property<string>("LastRepositoryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_repository_id");

                    b.HasKey("SingletonId");

                    b.HasIndex("LastRepositoryId");

                    b.ToTable("application_state", null, t =>
                        {
                            t.HasCheckConstraint("CK_application_state_color_theme", "color_theme IS NULL OR color_theme IN ('light', 'dark')");

                            t.HasCheckConstraint("CK_application_state_singleton", "singleton_id = 1");
                        });
                });

            modelBuilder.Entity("ChangeLens.Infrastructure.LocalState.Persistence.Entities.LocalStateMetadata", b =>
                {
                    b.Property<int>("SingletonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("singleton_id");

                    b.Property<long>("CreatedAtUnixMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_unix_ms");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("product_name");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schema_version");

                    b.HasKey("SingletonId");

                    b.ToTable("local_state_metadata", null, t =>
                        {
                            t.HasCheckConstraint("CK_local_state_metadata_product", "product_name = 'ChangeLens'");

                            t.HasCheckConstraint("CK_local_state_metadata_schema", "schema_version > 0");

                            t.HasCheckConstraint("CK_local_state_metadata_singleton", "singleton_id = 1");
                        });
                });

            modelBuilder.Entity("ChangeLens.Infrastructure.LocalState.Persistence.Entities.RepositoryLocalState", b =>
                {
                    b.Property<string>("RepositoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("repository_id");

                    b.Property<string>("CanonicalPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("canonical_path");

                    b.Property<string>("CanonicalPathKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("canonical_path_key");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<long>("LastOpenedAtUnixMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_opened_at_unix_ms");

                    b.Property<string>("PreferredTargetFullName")
                        .HasColumnType("TEXT")
                        .HasColumnName("preferred_target_full_name");

                    b.HasKey("RepositoryId");

                    b.HasIndex("CanonicalPathKey")
                        .IsUnique();

                    b.ToTable("repositories", (string)null);
                });

            modelBuilder.Entity("ChangeLens.Infrastructure.LocalState.Persistence.Entities.ApplicationLocalState", b =>
                {
                    b.HasOne("ChangeLens.Infrastructure.LocalState.Persistence.Entities.RepositoryLocalState", "LastRepository")
                        .WithMany()
                        .HasForeignKey("LastRepositoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LastRepository");
                });
#pragma warning restore 612, 618
        }
    }
}
