// <auto-generated />
using ChangeLens.Infrastructure.LocalState.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChangeLens.Infrastructure.LocalState.Persistence.Migrations
{
    [DbContext(typeof(ChangeLensLocalStateDbContext))]
    [Migration("20260802093824_AddSnapshotCapture")]
    partial class AddSnapshotCapture
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ChangeLens.Infrastructure.AnalysisRuns.Persistence.Entities.AnalysisRunEntity", b =>
                {
                    b.Property<string>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<long?>("AnalysisStartedAtUnixMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("analysis_started_at_unix_ms");

                    b.Property<long?>("CancellationRequestedAtUnixMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cancellation_requested_at_unix_ms");

                    b.Property<string>("CanonicalRepositoryPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("canonical_repository_path");

                    b.Property<string>("CanonicalRepositoryPathKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("canonical_repository_path_key");

                    b.Property<long?>("CaptureStartedAtUnixMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("capture_started_at_unix_ms");

                    b.Property<long?>("CapturedAtUnixMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("captured_at_unix_ms");

                    b.Property<int?>("CapturedChangedFileCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("captured_changed_file_count");

                    b.Property<string>("ChangeContext")
                        .HasColumnType("TEXT")
                        .HasColumnName("change_context");

                    b.Property<int?>("ExcludedConflictedCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("excluded_conflicted_count");

                    b.Property<int?>("ExcludedStagedCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("excluded_staged_count");

                    b.Property<int?>("ExcludedUncommittedTotal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("excluded_uncommitted_total");

                    b.Property<int?>("ExcludedUnstagedCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("excluded_unstaged_count");

                    b.Property<int?>("ExcludedUntrackedCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("excluded_untracked_count");

                    b.Property<string>("FreshnessToken")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("freshness_token");

                    b.Property<string>("HeadRevision")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("head_revision");

                    b.Property<string>("HeadRevisionAtCapture")
                        .HasColumnType("TEXT")
                        .HasColumnName("head_revision_at_capture");

                    b.Property<long?>("InterruptedAtUnixMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("interrupted_at_unix_ms");

                    b.Property<string>("InterruptionReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("interruption_reason");

                    b.Property<string>("ManifestHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("manifest_hash");

                    b.Property<string>("MergeBaseRevision")
                        .HasColumnType("TEXT")
                        .HasColumnName("merge_base_revision");

                    b.Property<string>("RepositoryDisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("repository_display_name");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("repository_id");

                    b.Property<long>("RequestedAtUnixMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requested_at_unix_ms");

                    b.Property<string>("SnapshotId")
                        .HasColumnType("TEXT")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target");

                    b.Property<string>("TargetRevision")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_revision");

                    b.Property<string>("TargetRevisionAtCapture")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_revision_at_capture");

                    b.Property<long?>("TerminalAtUnixMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("terminal_at_unix_ms");

                    b.Property<string>("TerminalFailureCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("terminal_failure_code");

                    b.Property<int?>("TerminalLimitationCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("terminal_limitation_count");

                    b.HasKey("RunId");

                    b.HasIndex("CanonicalRepositoryPathKey")
                        .IsUnique()
                        .HasDatabaseName("IX_analysis_runs_active_repository")
                        .HasFilter("state IN ('pendingCapture','capturing','discovering','collecting','persisting')");

                    b.ToTable("analysis_runs", null, t =>
                        {
                            t.HasCheckConstraint("CK_analysis_runs_capture_counts", "(captured_changed_file_count IS NULL OR captured_changed_file_count >= 0) AND (excluded_uncommitted_total IS NULL OR excluded_uncommitted_total >= 0) AND (excluded_staged_count IS NULL OR excluded_staged_count >= 0) AND (excluded_unstaged_count IS NULL OR excluded_unstaged_count >= 0) AND (excluded_untracked_count IS NULL OR excluded_untracked_count >= 0) AND (excluded_conflicted_count IS NULL OR excluded_conflicted_count >= 0)");

                            t.HasCheckConstraint("CK_analysis_runs_capture_fields", "(captured_at_unix_ms IS NULL AND snapshot_id IS NULL AND manifest_hash IS NULL AND target_revision_at_capture IS NULL AND head_revision_at_capture IS NULL AND merge_base_revision IS NULL AND captured_changed_file_count IS NULL AND excluded_uncommitted_total IS NULL AND excluded_staged_count IS NULL AND excluded_unstaged_count IS NULL AND excluded_untracked_count IS NULL AND excluded_conflicted_count IS NULL) OR (captured_at_unix_ms IS NOT NULL AND snapshot_id IS NOT NULL AND manifest_hash IS NOT NULL AND target_revision_at_capture IS NOT NULL AND head_revision_at_capture IS NOT NULL AND merge_base_revision IS NOT NULL AND captured_changed_file_count IS NOT NULL AND excluded_uncommitted_total IS NOT NULL AND excluded_staged_count IS NOT NULL AND excluded_unstaged_count IS NOT NULL AND excluded_untracked_count IS NOT NULL AND excluded_conflicted_count IS NOT NULL)");

                            t.HasCheckConstraint("CK_analysis_runs_interruption_fields", "(state = 'interrupted' AND interrupted_at_unix_ms IS NOT NULL) OR (state <> 'interrupted' AND interrupted_at_unix_ms IS NULL)");

                            t.HasCheckConstraint("CK_analysis_runs_manifest_hash", "manifest_hash IS NULL OR (length(manifest_hash) = 64 AND manifest_hash NOT GLOB '*[^0-9a-f]*')");

                            t.HasCheckConstraint("CK_analysis_runs_state", "state IN ('pendingCapture','capturing','discovering','collecting','persisting','completed','completedWithLimitations','cancelled','failed','interrupted')");

                            t.HasCheckConstraint("CK_analysis_runs_terminal_fields", "(state NOT IN ('completed','completedWithLimitations','cancelled','failed') AND terminal_at_unix_ms IS NULL) OR (state IN ('completed','completedWithLimitations','cancelled','failed') AND terminal_at_unix_ms IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ChangeLens.Infrastructure.AnalysisRuns.Persistence.Entities.AnalysisRunStepEntity", b =>
                {
                    b.Property<string>("RunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<string>("StepId")
                        .HasColumnType("TEXT")
                        .HasColumnName("step_id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("capability");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<long?>("FinishedAtUnixMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("finished_at_unix_ms");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("step_order");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("producer");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stage");

                    b.Property<long?>("StartedAtUnixMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started_at_unix_ms");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.HasKey("RunId", "StepId");

                    b.HasIndex("RunId", "Order")
                        .IsUnique();

                    b.ToTable("analysis_run_steps", null, t =>
                        {
                            t.HasCheckConstraint("CK_analysis_run_steps_state", "state IN ('pending','running','succeeded','succeededWithLimitations','failed','skipped','cancelled','timedOut')");
                        });
                });

            modelBuilder.Entity("ChangeLens.Infrastructure.LocalState.Persistence.Entities.ApplicationLocalState", b =>
                {
                    b.Property<int>("SingletonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("singleton_id");

                    b.Property<string>("ColorTheme")
                        .HasColumnType("TEXT")
                        .HasColumnName("color_theme");

                    b.Property<string>("LastRepositoryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_repository_id");

                    b.HasKey("SingletonId");

                    b.HasIndex("LastRepositoryId");

                    b.ToTable("application_state", null, t =>
                        {
                            t.HasCheckConstraint("CK_application_state_color_theme", "color_theme IS NULL OR color_theme IN ('light', 'dark')");

                            t.HasCheckConstraint("CK_application_state_singleton", "singleton_id = 1");
                        });
                });

            modelBuilder.Entity("ChangeLens.Infrastructure.LocalState.Persistence.Entities.LocalStateMetadata", b =>
                {
                    b.Property<int>("SingletonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("singleton_id");

                    b.Property<long>("CreatedAtUnixMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_unix_ms");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("product_name");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schema_version");

                    b.HasKey("SingletonId");

                    b.ToTable("local_state_metadata", null, t =>
                        {
                            t.HasCheckConstraint("CK_local_state_metadata_product", "product_name = 'ChangeLens'");

                            t.HasCheckConstraint("CK_local_state_metadata_schema", "schema_version > 0");

                            t.HasCheckConstraint("CK_local_state_metadata_singleton", "singleton_id = 1");
                        });
                });

            modelBuilder.Entity("ChangeLens.Infrastructure.LocalState.Persistence.Entities.RepositoryLocalState", b =>
                {
                    b.Property<string>("RepositoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("repository_id");

                    b.Property<string>("CanonicalPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("canonical_path");

                    b.Property<string>("CanonicalPathKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("canonical_path_key");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<long>("LastOpenedAtUnixMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_opened_at_unix_ms");

                    b.Property<string>("PreferredTargetFullName")
                        .HasColumnType("TEXT")
                        .HasColumnName("preferred_target_full_name");

                    b.HasKey("RepositoryId");

                    b.HasIndex("CanonicalPathKey")
                        .IsUnique();

                    b.ToTable("repositories", (string)null);
                });

            modelBuilder.Entity("ChangeLens.Infrastructure.Snapshots.Persistence.Entities.SnapshotManifestEntryEntity", b =>
                {
                    b.Property<string>("RunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("HeadEntryMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("head_entry_mode");

                    b.Property<string>("HeadObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("head_object_id");

                    b.Property<string>("MergeBaseEntryMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("merge_base_entry_mode");

                    b.Property<string>("MergeBaseObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("merge_base_object_id");

                    b.Property<string>("OriginalPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("original_path");

                    b.HasKey("RunId", "Path");

                    b.ToTable("snapshot_manifest_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_snapshot_manifest_entries_category", "category IN ('added','modified','deleted','renamed','typeChanged')");

                            t.HasCheckConstraint("CK_snapshot_manifest_entries_modes", "merge_base_entry_mode IN ('000000','100644','100755','120000','160000') AND head_entry_mode IN ('000000','100644','100755','120000','160000')");

                            t.HasCheckConstraint("CK_snapshot_manifest_entries_object_ids", "length(merge_base_object_id) = length(head_object_id) AND length(head_object_id) IN (40, 64) AND merge_base_object_id NOT GLOB '*[^0-9a-f]*' AND head_object_id NOT GLOB '*[^0-9a-f]*'");

                            t.HasCheckConstraint("CK_snapshot_manifest_entries_original_path", "(category = 'renamed' AND original_path IS NOT NULL) OR (category <> 'renamed' AND original_path IS NULL)");
                        });
                });

            modelBuilder.Entity("ChangeLens.Infrastructure.AnalysisRuns.Persistence.Entities.AnalysisRunStepEntity", b =>
                {
                    b.HasOne("ChangeLens.Infrastructure.AnalysisRuns.Persistence.Entities.AnalysisRunEntity", "Run")
                        .WithMany("Steps")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ChangeLens.Infrastructure.LocalState.Persistence.Entities.ApplicationLocalState", b =>
                {
                    b.HasOne("ChangeLens.Infrastructure.LocalState.Persistence.Entities.RepositoryLocalState", "LastRepository")
                        .WithMany()
                        .HasForeignKey("LastRepositoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LastRepository");
                });

            modelBuilder.Entity("ChangeLens.Infrastructure.Snapshots.Persistence.Entities.SnapshotManifestEntryEntity", b =>
                {
                    b.HasOne("ChangeLens.Infrastructure.AnalysisRuns.Persistence.Entities.AnalysisRunEntity", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ChangeLens.Infrastructure.AnalysisRuns.Persistence.Entities.AnalysisRunEntity", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
