// <auto-generated />
using ChangeLens.Infrastructure.LocalState.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChangeLens.Infrastructure.LocalState.Persistence.Migrations
{
    [DbContext(typeof(ChangeLensLocalStateDbContext))]
    partial class ChangeLensLocalStateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ChangeLens.Infrastructure.AnalysisRuns.Persistence.Entities.AnalysisRunEntity", b =>
                {
                    b.Property<string>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<long?>("AnalysisStartedAtUnixMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("analysis_started_at_unix_ms");

                    b.Property<long?>("CancellationRequestedAtUnixMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cancellation_requested_at_unix_ms");

                    b.Property<string>("CanonicalRepositoryPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("canonical_repository_path");

                    b.Property<string>("CanonicalRepositoryPathKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("canonical_repository_path_key");

                    b.Property<long?>("CaptureStartedAtUnixMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("capture_started_at_unix_ms");

                    b.Property<long?>("CapturedAtUnixMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("captured_at_unix_ms");

                    b.Property<string>("ChangeContext")
                        .HasColumnType("TEXT")
                        .HasColumnName("change_context");

                    b.Property<string>("FreshnessToken")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("freshness_token");

                    b.Property<string>("HeadRevision")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("head_revision");

                    b.Property<long?>("InterruptedAtUnixMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("interrupted_at_unix_ms");

                    b.Property<string>("InterruptionReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("interruption_reason");

                    b.Property<string>("RepositoryDisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("repository_display_name");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("repository_id");

                    b.Property<long>("RequestedAtUnixMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requested_at_unix_ms");

                    b.Property<string>("SnapshotId")
                        .HasColumnType("TEXT")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target");

                    b.Property<string>("TargetRevision")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_revision");

                    b.Property<long?>("TerminalAtUnixMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("terminal_at_unix_ms");

                    b.Property<string>("TerminalFailureCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("terminal_failure_code");

                    b.Property<int?>("TerminalLimitationCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("terminal_limitation_count");

                    b.HasKey("RunId");

                    b.HasIndex("CanonicalRepositoryPathKey")
                        .IsUnique()
                        .HasDatabaseName("IX_analysis_runs_active_repository")
                        .HasFilter("state IN ('pendingCapture','capturing','discovering','collecting','persisting')");

                    b.ToTable("analysis_runs", null, t =>
                        {
                            t.HasCheckConstraint("CK_analysis_runs_interruption_fields", "(state = 'interrupted' AND interrupted_at_unix_ms IS NOT NULL) OR (state <> 'interrupted' AND interrupted_at_unix_ms IS NULL)");

                            t.HasCheckConstraint("CK_analysis_runs_state", "state IN ('pendingCapture','capturing','discovering','collecting','persisting','completed','completedWithLimitations','cancelled','failed','interrupted')");

                            t.HasCheckConstraint("CK_analysis_runs_terminal_fields", "(state NOT IN ('completed','completedWithLimitations','cancelled','failed') AND terminal_at_unix_ms IS NULL) OR (state IN ('completed','completedWithLimitations','cancelled','failed') AND terminal_at_unix_ms IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ChangeLens.Infrastructure.AnalysisRuns.Persistence.Entities.AnalysisRunStepEntity", b =>
                {
                    b.Property<string>("RunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<string>("StepId")
                        .HasColumnType("TEXT")
                        .HasColumnName("step_id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("capability");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<long?>("FinishedAtUnixMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("finished_at_unix_ms");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("step_order");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("producer");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stage");

                    b.Property<long?>("StartedAtUnixMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started_at_unix_ms");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.HasKey("RunId", "StepId");

                    b.HasIndex("RunId", "Order")
                        .IsUnique();

                    b.ToTable("analysis_run_steps", null, t =>
                        {
                            t.HasCheckConstraint("CK_analysis_run_steps_state", "state IN ('pending','running','succeeded','succeededWithLimitations','failed','skipped','cancelled','timedOut')");
                        });
                });

            modelBuilder.Entity("ChangeLens.Infrastructure.LocalState.Persistence.Entities.ApplicationLocalState", b =>
                {
                    b.Property<int>("SingletonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("singleton_id");

                    b.Property<string>("ColorTheme")
                        .HasColumnType("TEXT")
                        .HasColumnName("color_theme");

                    b.Property<string>("LastRepositoryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_repository_id");

                    b.HasKey("SingletonId");

                    b.HasIndex("LastRepositoryId");

                    b.ToTable("application_state", null, t =>
                        {
                            t.HasCheckConstraint("CK_application_state_color_theme", "color_theme IS NULL OR color_theme IN ('light', 'dark')");

                            t.HasCheckConstraint("CK_application_state_singleton", "singleton_id = 1");
                        });
                });

            modelBuilder.Entity("ChangeLens.Infrastructure.LocalState.Persistence.Entities.LocalStateMetadata", b =>
                {
                    b.Property<int>("SingletonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("singleton_id");

                    b.Property<long>("CreatedAtUnixMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_unix_ms");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("product_name");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schema_version");

                    b.HasKey("SingletonId");

                    b.ToTable("local_state_metadata", null, t =>
                        {
                            t.HasCheckConstraint("CK_local_state_metadata_product", "product_name = 'ChangeLens'");

                            t.HasCheckConstraint("CK_local_state_metadata_schema", "schema_version > 0");

                            t.HasCheckConstraint("CK_local_state_metadata_singleton", "singleton_id = 1");
                        });
                });

            modelBuilder.Entity("ChangeLens.Infrastructure.LocalState.Persistence.Entities.RepositoryLocalState", b =>
                {
                    b.Property<string>("RepositoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("repository_id");

                    b.Property<string>("CanonicalPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("canonical_path");

                    b.Property<string>("CanonicalPathKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("canonical_path_key");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<long>("LastOpenedAtUnixMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_opened_at_unix_ms");

                    b.Property<string>("PreferredTargetFullName")
                        .HasColumnType("TEXT")
                        .HasColumnName("preferred_target_full_name");

                    b.HasKey("RepositoryId");

                    b.HasIndex("CanonicalPathKey")
                        .IsUnique();

                    b.ToTable("repositories", (string)null);
                });

            modelBuilder.Entity("ChangeLens.Infrastructure.AnalysisRuns.Persistence.Entities.AnalysisRunStepEntity", b =>
                {
                    b.HasOne("ChangeLens.Infrastructure.AnalysisRuns.Persistence.Entities.AnalysisRunEntity", "Run")
                        .WithMany("Steps")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ChangeLens.Infrastructure.LocalState.Persistence.Entities.ApplicationLocalState", b =>
                {
                    b.HasOne("ChangeLens.Infrastructure.LocalState.Persistence.Entities.RepositoryLocalState", "LastRepository")
                        .WithMany()
                        .HasForeignKey("LastRepositoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LastRepository");
                });

            modelBuilder.Entity("ChangeLens.Infrastructure.AnalysisRuns.Persistence.Entities.AnalysisRunEntity", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
